### ISSUE TITLE
能否给个运行代码的例子?

### ISSUE THREAD

**Issue by codezealer** [Moskize91/TaolanTutorial#2]
我下载了代码，发现没有办法运行这些代码。
能否给个运行代码的例子？

**Comment by Lurkrazy** [comment]
看了他的gitbook，他只写到了语法分析器，后面还有好多没写，所以这不是一个完整的编译器，你可以找一部分前面的代码看懂，然后修改一下单独运行。

**Comment by codezealer** [comment]
不，代码已经写完了，只不过文章没写完而已。我已经知道怎么运行代码了，很简单。
    		String path = Thread.currentThread().getContextClassLoader().getResource("").getPath() 
						+ File.separator + "scripts" + File.separator + "test.t";
		File file = new File(path);
		FileInputStream fis = new FileInputStream(file);
		InputStreamReader isr = new InputStreamReader(fis);
		VirtualMachine vm = VirtualMachine.instance();
		vm.run(isr);
这样就可以了。

**Comment by OumaSyuu** [comment]
@codezealer 并没有写完吧，我看他RunTime这个类里面的两个流都没用到，应该不会输出编译后的代码吧
